[package]
name = "nytuo-launcher"
version = "4.0.1"
description = "Nytuo Launcher - A modern game launcher for Nytuo's games"
authors = ["Nytuo"]
license = "GNU GPL V3-only"
repository = "https://github.com/Nytuo/Nytuo-Launcher"
edition = "2021"
rust-version = "1.77.2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "nytuo_launcher_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.5.6", features = [] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
log = "0.4"
tauri = { version = "2.10.3", features = [] }
tauri-plugin-log = "2"
tauri-plugin-sql = { version = "^2.0.0", features = ["sqlite"] }
tauri-plugin-shell = "^2.0.0"
tauri-plugin-updater = "2"
tauri-plugin-opener = "2"
url = "2"
tracing = "0.1"
reqwest = { version = "0.12", features = ["json", "blocking", "stream"] }
tokio = { version = "1.39", features = ["full"] }
futures-util = "0.3.32"
tauri-plugin-dialog = "^2.0.0"
sha2 = "0.10.9"
