name: Auto approve

on:
  pull_request

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    steps:
    - uses: ahmadnassri/action-dependabot-auto-merge@latest
      with:
        target: patch
        github-token: ${{ secrets.GITHUB_TOKEN }}
