name: Build/release
on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 10
      - name: Run a yarn or npm command
        uses: Adzz/yarn_command_action@v1.0.0
        with:
          command:  |
            cd Project
            yarn devBuild
      - name: "Build & test"
        run: |
          echo "done!"
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            dist/*.exe
            dist/*.blockmap
            dist/*.zip
            dist/*.snap
            dist/latest.yml
      - uses: actions/checkout@v2.2.0
        with:
          fetch-depth: 0
      - name: 'Get Previous tag'
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"

      - name: 'Writting'
        uses: DamianReeves/write-file-action@v1.0
        with:
          path: ${{ github.workspace}}/Version.txt
          contents: |
            ${{ steps.previoustag.outputs.tag }}
          write-mode: overwrite
      - name: "Pushing"
        uses: actions-go/push@master
        with:
          commit-message: '[Auto] Version file updated'
          remote: origin
