name: Build/release
on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
  
jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2.2.0

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 14
      - name: Setting the Path for Windows
        working-directory: ./Project
        if: matrix.os == 'windows-latest'
        run: |
            yarn install
            yarn devBuild
      - name: Setting the Path for Linux
        if: matrix.os == 'ubuntu-latest'
        working-directory: ./Project
        run: |
            yarn install
            yarn devBuild
            yarn electron-builder --x64 --win
        
      - name: Publishing For Windows
        if: matrix.os == 'windows-latest'
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          draft: true
          files: |
            Project/dist/*.exe
            Project/dist/*.blockmap
            Project/dist/*.zip
            Project/dist/latest.yml
      - name: Publishing for Linux
        if: matrix.os == 'ubuntu-latest'
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          draft: true
          files: |
            ${{github.workspace}}/Project/dist/*.zip
            ${{github.workspace}}/Project/dist/*.snap
            ${{github.workspace}}/Project/dist/*.exe
            ${{github.workspace}}/Project/dist/*.blockmap
            ${{github.workspace}}/Project/dist/latest.yml

