name: Build/release
on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
  
jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2.2.0

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 14
      - name: Setting the Path for Windows
        working-directory: ./Project
        if: matrix.os == 'windows-latest'
        run: |
            yarn install
            yarn devBuild
      - name: Setting the Path for Linux
        if: matrix.os == 'ubuntu-latest'
        working-directory: ./Project
        run: |
            sudo dpkg --add-architecture i386
            sudo apt update
            sudo apt install wine64
            sudo apt install wine32
            
            yarn install
            yarn devBuild
            yarn electron-builder --x64 --win -p never
        
      - name: Publishing For Windows
        if: matrix.os == 'windows-latest'
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            Project/dist/*.exe
            Project/dist/*.blockmap
            Project/dist/*.zip
            Project/dist/latest.yml
      - name: Publishing for Linux
        if: matrix.os == 'ubuntu-latest'
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            ${{github.workspace}}/Project/dist/*.zip
            ${{github.workspace}}/Project/dist/*.snap
            ${{github.workspace}}/Project/dist/*.exe
            ${{github.workspace}}/Project/dist/*.blockmap
            ${{github.workspace}}/Project/dist/latest.yml

  PushVersion:
    needs: release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.2.0
      with:
        fetch-depth: 0
    - name: 'Get Previous tag'
      id: previoustag
      uses: "WyriHaximus/github-action-get-previous-tag@v1"

    - name: 'Writting'
      uses: DamianReeves/write-file-action@v1.0
      with:
        path: ${{ github.workspace}}/Version.txt
        contents: |
          ${{ steps.previoustag.outputs.tag }}
        write-mode: overwrite
    - name: push
      uses: github-actions-x/commit@v2.8
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        push-branch: 'master'
        commit-message: 'Automated Version Update'
        force-add: 'true'
        name: JARVIS [BOT]
        email: nytuo.yt@gmail.com
