name: Build/release
on:
  push:
    tags:
      - "v*"
  schedule:
    - cron:  '0 17 * * 1'
  workflow_dispatch:
jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2.2.0

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 14
      - name: Get Package Version
        uses: nyaa8/package-version@v1
        with:
          path: 'Project/package.json'
          
      - uses: actions/checkout@v2.2.0
        with:
          fetch-depth: 0
      - name: 'Get Previous tag'
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
      - run: echo ${{env.PKGVER}}  
      - if: ${{ steps.previoustag.outputs.tag != env.PKGVER }}
        name: Setting the path and publishing
        working-directory: ./Project
        run: |
            sudo dpkg --add-architecture i386
            sudo apt update
            sudo apt install wine64
            sudo apt install wine32
            
            yarn install
            yarn devBuild
            yarn electron-builder --x64 --win -p never        
        env:
          PKGVER: v${{env.PACKAGE_VERSION}}
      
      - if: ${{ steps.previoustag.outputs.tag != env.PKGVER }}
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          automatic_release_tag: ${{env.PKGVER}}
          files: |
            ${{github.workspace}}/Project/dist/*.zip
            ${{github.workspace}}/Project/dist/*.snap
            ${{github.workspace}}/Project/dist/*.exe
            ${{github.workspace}}/Project/dist/*.blockmap
            ${{github.workspace}}/Project/dist/latest.yml
            ${{github.workspace}}/Project/dist/*.deb
            ${{github.workspace}}/Project/dist/*.AppImage
        env:
          PKGVER: v${{env.PACKAGE_VERSION}}

  PushVersion:
    needs: release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.2.0
      with:
        fetch-depth: 0
    - name: 'Get Previous tag'
      id: previoustag
      uses: "WyriHaximus/github-action-get-previous-tag@v1"

    - name: 'Writting'
      uses: DamianReeves/write-file-action@v1.0
      with:
        path: ${{ github.workspace}}/Version.txt
        contents: |
          ${{ steps.previoustag.outputs.tag }}
        write-mode: overwrite
    - name: push
      uses: github-actions-x/commit@v2.8
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        push-branch: 'master'
        commit-message: 'Automated Version Update'
        force-add: 'true'
        name: JARVIS [BOT]
        email: nytuo.yt@gmail.com
