name: Build/release
on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
  
jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2.2.0

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 14
      - name: Setting the Path
        run: |
            cd ${{github.workspace}}/Project
            yarn install
            yarn devBuild
            docker run --rm -ti \
            --env-file <(env | grep -iE 'DEBUG|NODE_|ELECTRON_|YARN_|NPM_|CI|CIRCLE|TRAVIS_TAG|TRAVIS|TRAVIS_REPO_|TRAVIS_BUILD_|TRAVIS_BRANCH|TRAVIS_PULL_REQUEST_|APPVEYOR_|CSC_|GH_|GITHUB_|BT_|AWS_|STRIP|BUILD_') \
            --env ELECTRON_CACHE="/root/.cache/electron" \
            --env ELECTRON_BUILDER_CACHE="/root/.cache/electron-builder" \
            -v ${PWD}:/project \
            -v ${PWD##*/}-node-modules:/project/node_modules \
            -v ~/.cache/electron:/root/.cache/electron \
            -v ~/.cache/electron-builder:/root/.cache/electron-builder \
            electronuserland/builder:wine
            /bin/bash -c "yarn && yarn dist"
      - name: Publishing
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            ${{github.workspace}}/Project/dist/*.exe
            ${{github.workspace}}/Project/dist/*.blockmap
            ${{github.workspace}}/Project/dist/*.zip
            ${{github.workspace}}/Project/dist/latest.yml
            ${{github.workspace}}/Project/dist/*.zip
            ${{github.workspace}}/Project/dist/*.snap
