name: Build/release
on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
  
jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2.2.0

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 14
      - name: Setting the Path
        run: |
            cd ${{github.workspace}}/Project
            SET GH_TOKEN=${{secrets.GITTOKKEN}}
            yarn install
            yarn devBuild
      - name: Publishing
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            ${{github.workspace}}/Project/dist/*.exe
            ${{github.workspace}}/Project/dist/*.blockmap
            ${{github.workspace}}/Project/dist/*.zip
            ${{github.workspace}}/Project/dist/latest.yml
            ${{github.workspace}}/Project/dist/*.zip
            ${{github.workspace}}/Project/dist/*.snap
