name: Build/release
on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
  
jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - working-directory: ./Project
      - name: Check out Git repository
        uses: actions/checkout@v2.2.0

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 14
      - name: Setting the Path for Windows
        if: matrix.os == 'windows-latest'
        run: |
            yarn install
            yarn devBuild
      - name: Setting the Path for Linux
        if: matrix.os == 'ubuntu-latest'
        run: |
            yarn install
            yarn devBuild
      - name: Publishing For Windows
        if: matrix.os == 'windows-latest'
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          draft: true
          files: |
            dist/*.exe
            dist/*.blockmap
            dist/*.zip
            dist/latest.yml
      - name: Publishing for Linux
        if: matrix.os == 'ubuntu-latest'
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          draft: true
          files: |
            dist/*.zip
            dist/*.snap
  deploy:
    needs: release
    runs-on: ubuntu-latest
    steps:
      - name: Publish Release
  # You may pin to the exact commit or the version.
  # uses: eregon/publish-release@d6aee8c288e653387d895ee64d559fc0dd63339d
        uses: eregon/publish-release@v1.0.3
        with:
    # The ID of the draft release to publish
          release_id: 4
  WrittingVersionFile:
    needs: [release,deploy]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.2.0
      with:
        fetch-depth: 0
    - name: 'Get Previous tag'
      id: previoustag
      uses: "WyriHaximus/github-action-get-previous-tag@v1"

    - name: 'Writting'
      uses: DamianReeves/write-file-action@v1.0
      with:
        path: ${{ github.workspace}}/Version.txt
        contents: |
          ${{ steps.previoustag.outputs.tag }}
        write-mode: overwrite
    - name: "Pushing"
      uses: actions-go/push@master
      with:
        commit-message: '[Auto] Version file updated'
        remote: origin
