name: Build/release
on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 14
      - name: Setting the Path for Windows
        if: matrix.os == 'windows-latest'
        run: |
            cd ${{github.workspace}}/Project
            SET GH_TOKEN=${{secrets.GITTOKKEN}}
            yarn install
            yarn devBuild
      - name: Setting the Path for Linux
        if: matrix.os == 'ubuntu-latest'
        run: |
            cd ${{github.workspace}}/Project
            export GH_TOKEN=${{secrets.GITTOKKEN}}
            yarn install
            yarn devBuild
      - name: "Build & test"
        run: |
          echo "done!"
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            ${{github.workspace}}/Project/dist/*.exe
            ${{github.workspace}}/Project/dist/*.blockmap
            ${{github.workspace}}/Project/dist/*.zip
            ${{github.workspace}}/Project/dist/*.snap
            ${{github.workspace}}/Project/dist/latest.yml
      - uses: actions/checkout@v2.2.0
        with:
          fetch-depth: 0
      - name: 'Get Previous tag'
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"

      - name: 'Writting'
        uses: DamianReeves/write-file-action@v1.0
        with:
          path: ${{ github.workspace}}/Version.txt
          contents: |
            ${{ steps.previoustag.outputs.tag }}
          write-mode: overwrite
      - name: "Pushing"
        uses: actions-go/push@master
        with:
          commit-message: '[Auto] Version file updated'
          remote: origin
