
name: "Increment PKGJSON"

on:
  pull_request:
    types: [closed]
  workflow_dispatch:

jobs:
  bump-version:
    name: "Bump Version on master"
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout source code"
        uses: "actions/checkout@v2"
      - name: "Get the Version"
        uses: MYXOMOPX/modify-pkg-json@master
        id: getcmnver
        with: 
          target: ./Project/package.json
          action: "get_version"
      - run: |
          echo '${{steps.getcmnver.outputs.result}}'
      - name: "ParseVersion"
        id: semver_parser 
        uses: booxmedialtd/ws-action-parse-semver@v1
        with:
          input_string: '${{steps.getcmnver.outputs.result}}'
      - name: "Modify Version"
        uses: MYXOMOPX/modify-pkg-json@master
        id: setcmnver
        with: 
          target: ./Project/package.json
          action: "set_version"
          argument: "${{ steps.semver_parser.outputs.major }}.${{steps.semver_parser.outputs.minor}}.${{steps.semver_parser.outputs.patch}}+1"
      - name: push
        uses: github-actions-x/commit@v2.8
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          push-branch: 'master'
          commit-message: 'Automated Package.Json Update'
          force-add: 'true'
          name: JARVIS [BOT]
          email: nytuo.yt@gmail.com
