name: VirusTotal Analysis

on:
  release:
    types: [published]
  workflow_dispatch:
jobs:
  virustotal:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.2.0
        with:
          fetch-depth: 0
      - name: 'Get Previous tag'
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
      -
        name: VirusTotal Scan
        uses: crazy-max/ghaction-virustotal@v2
        with:
          update_release_body: true
          vt_api_key: ${{ secrets.VT_API_KEY }}
          files: |
            ./Nytuo-Launcher.Setup.${{ steps.previoustag.outputs.tag }}.exe$
