name: VirusTotal Analysis

on:
  release:
    types: [published]
  workflow_dispatch:
jobs:
  virustotal:
    runs-on: ubuntu-latest
    steps:
      -
        name: VirusTotal Scan
        uses: crazy-max/ghaction-virustotal@v2
        with:
          update_release_body: true
          vt_api_key: ${{ secrets.VT_API_KEY }}
          files: |
            .exe$
            .AppImage$
            .deb$
            .zip$
            .snap$
