name: VirusTotal Analysis

on:
  release:
    types: [published]
  workflow_dispatch:
jobs:
  virustotal:
    runs-on: ubuntu-latest
    steps:
  #    - uses: actions/checkout@v2.2.0
   #   - name: Get Package Version
    #    uses: nyaa8/package-version@v1
     #   with:
      #    path: 'Project/package.json'
      -
        name: VirusTotal Scan
        uses: crazy-max/ghaction-virustotal@v2
        with:
          update_release_body: true
          vt_api_key: ${{ secrets.VT_API_KEY }}
          files: |
            .exe$
#            ./Nytuo-Launcher.Setup.${{env.PACKAGE_VERSION}}.exe
          # ./Nytuo-Launcher-${{env.PACKAGE_VERSION}}-win.zip
         # ./Nytuo-launcher-${{env.PACKAGE_VERSION}}.zip
          # ./Nytuo-Launcher-${{env.PACKAGE_VERSION}}.AppImage
 # ./nytuo-launcher_${{env.PACKAGE_VERSION}}_amd64.deb
# ./nytuo-launcher_${{env.PACKAGE_VERSION}}_amd64.snap
