name: Write Version to File
on:
  push:
    branches:
      - master

jobs:
  GetTheTag:
    runs-on: ubuntu-latest
    steps:
    - name: 'Get Previous tag'
      id: previoustag
      uses: "WyriHaximus/github-action-get-previous-tag@v1"
    - uses: actions/checkout@v2
    - name: 'Writting'
      uses: DamianReeves/write-file-action@v1.0
      with:
        path: ${{ github.workspace}}/Version.txt
        contents: |
          echo ${{ steps.previoustag.outputs.tag }}
        write-mode: overwrite
