name: WriteVersionFile
on:
  release:
    types: [published]
  workflow_dispatch:
jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2.2.0
      - name: 'Get Previous tag'
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"

      - name: 'Writting the tag in File'
        uses: DamianReeves/write-file-action@v1.0
        with:
          path: ${{ github.workspace}}/Version.txt
          contents: |
            ${{ steps.previoustag.outputs.tag }}
          write-mode: overwrite
      - name: "Pushing the change"
        uses: actions-go/push@master
        with:
          commit-message: '[Auto] Version file updated'
          remote: origin
